name: Ejercicoi 3.2 workflow

on: 
  pull_request:

jobs:					
  ejer3_2:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
    - name: Clonar c√≥digo
      uses: actions/checkout@v5

    - name: Lint
      uses: advanced-security/python-lint-code-scanning-action@v1
      with:
        linter: pylint
