name: Ejercicio 1 workflow

on: push

jobs:
  ejer1:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar c√≥digo
        uses: actions/checkout@v5

      - name: Instalar PyTest
        run: |
          pip install pytest

      - name: Ejecutar pytest.py
        run: |
          pytest test.py
        
